Set thread to unread
navikt/crm-arbeidsgiver-dialog pull request #280
Opened 2024-06-04 11:47 UTC by solsen

2024-06-10 07:36 UTC, solsen commented
Klar til review :) Kan noen se på denne når de har tid? @navikt/salesforce-arbeidsgiver

2024-06-10 08:50 UTC, raac09 requested changes
Se navnendring på flow

2024-06-11 07:29 UTC, solsen commented on package.json
Ja, måtte legge til babel for at eslint skal tolke disse linje 6,7 og 8 (med @) i tagFlowRedirect.js riktig.

2024-06-11 12:25 UTC, raac09 approved these changes

2024-06-11 12:30 UTC, merged